# Generated by Django 4.1 on 2025-02-25 05:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_alter_userprofile_physical_activity_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blood_pressure",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_completion_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vikruti",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="diet_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vegetarian", "Vegetarian"),
                    ("Vegan", "Vegan"),
                    ("Non-Vegetarian", "Non-Vegetarian"),
                    ("Pescatarian", "Pescatarian"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dosha_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vata", "Vata"),
                    ("Pitta", "Pitta"),
                    ("Kapha", "Kapha"),
                    ("Vata-Pitta", "Vata-Pitta"),
                    ("Pitta-Kapha", "Pitta-Kapha"),
                    ("Vata-Kapha", "Vata-Kapha"),
                    ("Tridosha", "Tridosha"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="physical_activity_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sedentary", "Less than 2 hours/week"),
                    ("Lightly Active", "2-4 hours/week"),
                    ("Active", "4-7 hours/week"),
                    ("Very Active", "More than 7 hours/week"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pulse_rate",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(250),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sleep_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Regular", "7-9 hours"),
                    ("Irregular", "Varying hours"),
                    ("Less than 6 hours", "Less than 6 hours"),
                    ("More than 9 hours", "More than 9 hours"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.CreateModel(
            name="HealthMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "blood_pressure",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("pulse_rate", models.IntegerField(blank=True, null=True)),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                (
                    "stress_level",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.userprofile",
                    ),
                ),
            ],
            options={"ordering": ["-date"],},
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_ai", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("general", "General Question"),
                            ("diagnosis", "Diagnosis"),
                            ("treatment", "Treatment"),
                            ("follow_up", "Follow Up"),
                            ("emergency", "Emergency"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("related_symptoms", models.TextField(blank=True, null=True)),
                ("ai_confidence_score", models.FloatField(blank=True, null=True)),
                ("needs_human_review", models.BooleanField(default=False)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["timestamp"],},
        ),
        migrations.CreateModel(
            name="AyurvedicRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("herbs", models.TextField(blank=True, null=True)),
                ("dietary_suggestions", models.TextField(blank=True, null=True)),
                ("lifestyle_changes", models.TextField(blank=True, null=True)),
                ("yoga_practices", models.TextField(blank=True, null=True)),
                ("is_followed", models.BooleanField(default=False)),
                (
                    "effectiveness_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("user_feedback", models.TextField(blank=True, null=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.chatmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.userprofile",
                    ),
                ),
            ],
            options={"ordering": ["-date_created"],},
        ),
    ]
