# Generated by Django 4.1 on 2025-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_userprofile_allergies_userprofile_blood_pressure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
