# Generated by Django 5.1.4 on 2025-03-23 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userprofile_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='healthmetric',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='chronic_conditions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_medications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='diet_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='family_medical_history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_checkup_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='physical_activity_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prakriti',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pulse_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sleep_pattern',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vikruti',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_year',
            field=models.IntegerField(blank=True, help_text='Year of birth (e.g., 1998)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, default='', help_text='Known allergies'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('AB+', 'AB-'), ('O+', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dosha_type',
            field=models.CharField(blank=True, choices=[('Vata', 'Vata'), ('Pitta', 'Pitta'), ('Kapha', 'Kapha'), ('Vata-Pitta', 'Vata-Pitta'), ('Pitta-Kapha', 'Pitta-Kapha'), ('Vata-Kapha', 'Vata-Kapha'), ('Tridoshic', 'Tridoshic')], default='', help_text='Select your Ayurvedic body type', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medical_history',
            field=models.TextField(blank=True, default='', help_text='Comma-separated past diseases or conditions'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True, default='')),
                ('user_message', models.TextField(blank=True, default='')),
                ('ai_response', models.TextField(blank=True, default='')),
                ('predictions', models.JSONField(blank=True, default=dict, help_text='Stores AI-generated predictions')),
                ('treatment', models.JSONField(blank=True, default=dict, help_text='Stores AI-recommended treatments')),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='AyurvedicRecommendation',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='HealthMetric',
        ),
    ]
