# Generated by Django 4.1 on 2025-03-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_chatmessage_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=7,
            ),
        ),
    ]
